## Recency, Frequency, and Money leading into K-Means clustering

Chet Huang, 27 Feb 2020

### Purpose
In this notebook we explore sales data from an online retailer.  This data has been posted to UC Irvine's machine learning data repository.  We use this data to identify customer groupings by recency, frequency, and monetary value.  This grouping or segmentation of customers can help the sales and marketing teams plan targeted campaigns to cultivate customer relationships.  Many such campaigns have goals related to improving a company's bottom line.

In [1]:
# Import necessary libraries
import pandas as pd
import datetime as dt
import numpy as np
from collections import OrderedDict
from sklearn.cluster import KMeans

In [2]:
# Read in data file and look at attribute names and data types
file = "https://archive.ics.uci.edu/ml/machine-learning-databases/00352/Online%20Retail.xlsx"
store = pd.read_excel(file)
store.dtypes

InvoiceNo              object
StockCode              object
Description            object
Quantity                int64
InvoiceDate    datetime64[ns]
UnitPrice             float64
CustomerID            float64
Country                object
dtype: object

In [3]:
print("Number of rows, columns: ",store.shape)

Number of rows, columns:  (541909, 8)


Let's check the date windows from our dataset.

In [4]:
ts = store.InvoiceDate
EarliestDate = min(store.InvoiceDate)
LatestDate = max(store.InvoiceDate)
print("Earliest date=%s, Latest date=%s", EarliestDate.strftime("%Y-%m-%d"), LatestDate.strftime("%Y-%m-%d"))

Earliest date=%s, Latest date=%s 2010-12-01 2011-12-09


We have just over a year's worth of sales data.  We could set boundaries on the dates of our analysis, but let's go ahead and use all transactions in the dataset.  We'll copy these transactions into a new dataframe and also add a new calculated column for the total Sales which is UnitPrice * Quantity.

In [5]:
#datemask = (store.OrderDate>=EarliestDate) & (store.OrderDate<CalculationDate)
transactionsRfm = store.copy()
transactionsRfm['Sales'] = transactionsRfm.Quantity * transactionsRfm.UnitPrice
transactionsRfm.head()

InvoiceNo StockCode                          Description  Quantity  \
0    536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6   
1    536365     71053                  WHITE METAL LANTERN         6   
2    536365    84406B       CREAM CUPID HEARTS COAT HANGER         8   
3    536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6   
4    536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6   

          InvoiceDate  UnitPrice  CustomerID         Country  Sales  
0 2010-12-01 08:26:00       2.55     17850.0  United Kingdom  15.30  
1 2010-12-01 08:26:00       3.39     17850.0  United Kingdom  20.34  
2 2010-12-01 08:26:00       2.75     17850.0  United Kingdom  22.00  
3 2010-12-01 08:26:00       3.39     17850.0  United Kingdom  20.34  
4 2010-12-01 08:26:00       3.39     17850.0  United Kingdom  20.34

To get recency, we need the last transaction for every customer

In [6]:
lastTransaction = transactionsRfm.groupby('CustomerID').InvoiceDate.max()
lastTransaction.head()

CustomerID
12346.0   2011-01-18 10:17:00
12347.0   2011-12-07 15:52:00
12348.0   2011-09-25 13:13:00
12349.0   2011-11-21 09:51:00
12350.0   2011-02-02 16:01:00
Name: InvoiceDate, dtype: datetime64[ns]

From recency date we calculate day elapsed then convert results to dataframe

In [7]:
rfm = (LatestDate - lastTransaction).dt.days
rfm = rfm.to_frame('Recency')
rfm.head()

Recency
CustomerID         
12346.0         325
12347.0           1
12348.0          74
12349.0          18
12350.0         309

Frequency requires us to count the number of tranactions by customer

In [8]:
rfm.loc[:,'Frequency'] = transactionsRfm.groupby('CustomerID').InvoiceNo.count()
rfm.head()

Recency  Frequency
CustomerID                    
12346.0         325          2
12347.0           1        182
12348.0          74         31
12349.0          18         73
12350.0         309         17

Money is a sum of the Sales attribute in the transaction

In [9]:
rfm.loc[:,'Money'] = transactionsRfm.groupby('CustomerID').Sales.sum()
rfm.head()

Recency  Frequency    Money
CustomerID                             
12346.0         325          2     0.00
12347.0           1        182  4310.00
12348.0          74         31  1797.24
12349.0          18         73  1757.55
12350.0         309         17   334.40

At this point we have a table of customers, their recency (days since last transaction), frequency of their transactions in the last year, and how much in sales they generated.  This table contains actionable information for our sales and marketing teams.  For example, high frequency & high money customers with high recency (many days since last transaction) may mean that the customer has churned.  Marketing may want to run campaigns to see if we can win these customers back.  Conversely, customers with low frequency, low money, but recent transactions may warrant futher cultivation for their continued patronage.

Let's take our RFM analysis a step further and segment this RFM list into groups to help our sales and marketing teams target relevant campaigns.  Let's use K-Means clustering to segment these customers.  Since we have three attributes, let's take a simple approach and divide each attribute into low or high.  This will effectively split the 3D space into 8 clusters  We will seed the K-Means clustering with centroids located at low and high along each axis.

To properly assign centroids, we also need to define what values constitute low or high.  Since each attribute in R, F, M are not similar in scale, we will use min-max normalization so that each attribute will only vary between 0 and 1.  Then for the centroids we can use 0.25 for low, and 0.75 for high.

In [10]:
def NormalizeColumn(data, columns):
    """
    This function applies min-max normalization.  Inputs are dataframe called
    data and array called columns
    """
    for each in columns:
        data.loc[:,each] = (data.loc[:,each] - np.min(data.loc[:,each])) \
            / (np.max(data.loc[:,each]) - np.min(data.loc[:,each]))
    return data

rfm_norm = NormalizeColumn(rfm, ['Recency','Frequency','Money'])
rfm_norm.head()

Recency  Frequency     Money
CustomerID                               
12346.0     0.871314   0.000125  0.015109
12347.0     0.002681   0.022676  0.030297
12348.0     0.198391   0.003758  0.021442
12349.0     0.048257   0.009020  0.021303
12350.0     0.828418   0.002005  0.016288

Now we're ready to use K-Means to find 8 clusters with seed centroids

In [11]:
k_centers = np.array([[0.25,0.25,0.25],[0.25,0.75,0.25],[0.25,0.25,0.75],[0.25,0.75,0.75],
                    [0.75,0.25,0.25],[0.75,0.25,0.75],[0.75,0.75,0.75],[0.75,0.75,0.25]], np.float64)
k_means = KMeans(n_clusters=8,init=k_centers,n_init=1).fit(rfm_norm)

# Let's print the clustered centers to see how far they've drifted from the seed
centers = k_means.cluster_centers_
print(centers)

[[0.29766908 0.00562291 0.01823263]
 [0.00268097 0.74079178 0.24337532]
 [0.02144772 0.12683538 0.69206358]
 [0.90729203 0.00279722 0.01624688]
 [0.48913683 0.00458046 0.01721598]
 [0.15217721 0.00754943 0.01886927]
 [0.69463429 0.0028102  0.01676095]
 [0.03733226 0.01777505 0.0247879 ]]


We see that the cluster centers have drifted quite a bit from the initial centers.  This suggests that the customers were not very evenly distributed across the high-low RFM space.  Such is the nature of our sales data.  Nevertheless, let's get the K-Means cluster labels.

In [12]:
k_means_predicted = k_means.predict(rfm_norm)
k_means_predicted

array([3, 7, 5, ..., 7, 7, 5])

We can now merge these labels back to our original rfm dataframe.

In [13]:
rfm['ClusterID'] = k_means_predicted
rfm

Recency  Frequency     Money  ClusterID
CustomerID                                          
12346.0     0.871314   0.000125  0.015109          3
12347.0     0.002681   0.022676  0.030297          7
12348.0     0.198391   0.003758  0.021442          5
12349.0     0.048257   0.009020  0.021303          7
12350.0     0.828418   0.002005  0.016288          3
12352.0     0.093834   0.011776  0.020555          7
12353.0     0.544236   0.000376  0.015423          4
12354.0     0.619303   0.007141  0.018913          6
12355.0     0.571046   0.001503  0.016728          4
12356.0     0.058981   0.007266  0.025016          7
12357.0     0.085791   0.016287  0.036984          7
12358.0     0.002681   0.002255  0.019225          7
12359.0     0.018767   0.031696  0.037118          7
12360.0     0.136729   0.016036  0.024490          5
12361.0     0.766756   0.001128  0.015778          6
12362.0     0.005362   0.034202  0.033273          7
12363.0     0.292225   0.002756  0.017054          0
12364.0     0.018767   0.010524  0.019736          7
12365.0     0.777480   0.002756  0.016239          6
12367.0     0.008043   0.001253  0.015704          7
12370.0     0.134048   0.020797  0.027604          5
12371.0     0.117962   0.007767  0.021762          5
12372.0     0.190349   0.006389  0.019683          5
12373.0     0.831099   0.001629  0.016394          3
12374.0     0.064343   0.004009  0.017727          7
12375.0     0.005362   0.002130  0.016714          7
12377.0     0.841823   0.009521  0.020847          3
12378.0     0.345845   0.027311  0.029235          0
12379.0     0.217158   0.005011  0.018106          5
12380.0     0.056300   0.013029  0.024696          7
...              ...        ...       ...        ...
18245.0     0.016086   0.022050  0.023946          7
18246.0     0.061662   0.000376  0.017210          7
18248.0     0.302949   0.006014  0.017868          0
18249.0     0.042895   0.000877  0.015445          7
18250.0     0.804290   0.002631  0.016318          3
18251.0     0.230563   0.001879  0.030314          0
18252.0     0.134048   0.012152  0.016965          5
18255.0     0.235925   0.000626  0.015473          0
18256.0     0.949062   0.000376  0.014933          3
18257.0     0.101877   0.015284  0.023092          5
18259.0     0.064343   0.005137  0.023350          7
18260.0     0.461126   0.017414  0.024254          4
18261.0     0.112601   0.002506  0.016252          5
18262.0     0.372654   0.001503  0.015636          0
18263.0     0.058981   0.007642  0.019377          7
18265.0     0.190349   0.005638  0.017934          5
18268.0     0.356568   0.000125  0.015109          0
18269.0     0.957105   0.000877  0.015599          3
18270.0     0.099196   0.001503  0.015951          5
18272.0     0.005362   0.021173  0.025909          7
18273.0     0.002681   0.000251  0.015828          7
18274.0     0.045576   0.002631  0.015109          7
18276.0     0.053619   0.001879  0.016249          7
18277.0     0.152815   0.001002  0.015453          5
18278.0     0.195710   0.001002  0.015722          5
18280.0     0.742627   0.001128  0.015746          6
18281.0     0.482574   0.000752  0.015394          4
18282.0     0.018767   0.001503  0.015731          7
18283.0     0.008043   0.094588  0.022491          7
18287.0     0.112601   0.008644  0.021584          5

[4372 rows x 4 columns]

## Summary

In this notebook we have read in sales data from an online retailer and performed RFM analysis on customer transactions for the last year.  From the RFM analysis we further segmented the customers using K-Means clustering.  There were 8 clusters, made up of upper and lower tiers along the Recency, Frequency, and Money axes.  This customer segmentation allows our sales and marketing teams to target campaigns to respective customer groups.  For example, high frequency customers who spent high amounts but have low recency may be churning.  Marketing should act upon this information and seek out ways to cultivate these high value customers.